#!/bin/bash


if [ $# -eq 1 ];then
	scp -r "talkmate@NameNode:/home/talkmate/share/$1" .
elif [ $# -eq 2 ];then
	scp -r "talkmate@NameNode:/home/talkmate/share/$1" "$2"
else
	echo "Usage: pull file [path]"
fi

